# Generated by Django 3.0.6 on 2021-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('B7', 'B7'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D4'), ('D5', 'D5'), ('D6', 'D6'), ('D7', 'D7')], max_length=4),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='showscreen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_id', 'screen')},
        ),
    ]
