# Generated by Django 3.2.5 on 2021-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210801_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
