# Generated by Django 3.2.5 on 2021-08-01 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210801_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 8, 1, 21, 28, 54, 543327)),
        ),
    ]
