# Generated by Django 3.2.5 on 2021-08-01 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_seat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 8, 1, 16, 3, 41, 10096, tzinfo=utc)),
        ),
    ]
