# Generated by Django 3.2.5 on 2021-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_seat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
