# Generated by Django 3.2.5 on 2021-08-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20210801_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_no',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
