# Generated by Django 3.2.5 on 2021-08-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20210801_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showscreen',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.screen'),
        ),
        migrations.AlterField(
            model_name='showscreen',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.show'),
        ),
        migrations.AlterUniqueTogether(
            name='showscreen',
            unique_together={('screen', 'show')},
        ),
    ]
